version: "3.4"
services:
  app:
    env_file: docker.env
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
